### ISSUE TITLE
chore: Migrate dimensions to dimens resources

### ISSUE THREAD

**Issue by jddeep** [AOSSIE-Org/Starcross-Android#1]
![starcross-dimens](https://user-images.githubusercontent.com/43133646/73949573-9a04ac00-4920-11ea-8398-0796e6d38520.png)

The dimension values from the layout file of Main Activity should be migrated and kept separately in dimens res directory.
I would like to work on this issue

**Comment by jddeep** [comment]
@makhanovable @raghavpuri31 @Thuva4 @prudhvir3ddy Can I work on this?

**Comment by prudhvir3ddy** [comment]
Contribute on gitlab
